#!/usr/bin/env python3

import math

import numpy as np
import pandas as pd
import rclpy
from geometry_msgs.msg import Point
from nav_msgs.msg import Odometry
from rclpy.node import Node
from sensor_msgs.msg import Imu
from std_msgs.msg import Float32, Int32


# =============================================================================
# RoboRacer ICRA 2026 - Competition-Legal Pure Pursuit at 100% CSV speed
# =============================================================================
#
# INPUTS USED BY THIS CONTROLLER
# ------------------------------
# Internal localization topics generated by our own stack:
#   /localization/odom        -> global X/Y
#   /odometry/filtered        -> high-rate vehicle speed
#
# Competition INPUT topic:
#   /autodrive/roboracer_1/imu
#
# OUTPUTS:
#   /autodrive/roboracer_1/steering_command
#   /autodrive/roboracer_1/throttle_command
#
# IMPORTANT:
# This controller DOES NOT subscribe to:
#   /autodrive/roboracer_1/ips
#   /autodrive/roboracer_1/odom
#   /tf
#   lap timing / collision-count / other restricted debugging topics
#
# The localization stack itself must also be built only from permitted sensor
# inputs (LiDAR, IMU, wheel encoders, steering, etc.).
#
# =============================================================================
# WHY THIS VERSION EXISTS
# =============================================================================
#
# The high-speed rosbag showed that localization was still accurate near the middle
# S-turn, but our added "turn-in gate" was forcing steering lookahead down to
# ~0.70 m while normal speed-based Pure Pursuit wanted ~2.0 m.
#
# That made steering about 2-3x more aggressive than the older successful
# IPS-based controller.
#
# THIS VERSION REMOVES THAT TURN-IN GATE COMPLETELY.
#
# Steering is again governed by the proven rule:
#
#     lookahead = clip(0.45 * speed, 0.70, 2.00)
#
# We keep:
#   - /localization/odom global position
#   - EKF speed
#   - IMU yaw / yaw rate
#   - measured steering-latency compensation
#   - local/monotonic path association
#   - offset lookahead
#   - feedforward throttle only
#   - curvature-dependent speed divisor:
#         fast sections  -> /1.15
#         tight sections -> smoothly approach /1.50
#
# No PID.
# No throttle cut.
# No restricted truth topics.
# =============================================================================


# =============================================================================
# MAIN RACING PARAMETERS
# =============================================================================

CONTROL_PERIOD = 0.020          # 50 Hz

# Fast/gentle sections.
VELOCITY_DIVISOR = 1.1

# Tight-corner protection remains at the already-proven safe level.
TIGHT_CORNER_DIVISOR = 1.50

# -------------------------------------------------------------------------
# COLD-START MANAGER
# -------------------------------------------------------------------------
#
# Flying laps are already proven at 100%: 13 clean laps around 10.2 s.
# Do NOT alter that steady-state behavior.
#
# The only special handling is for a controller start from rest.
#
# During the standing launch:
#   - use the proven /1.15 fast divisor temporarily,
#   - ramp throttle smoothly,
#   - wait for PF longitudinal covariance + wheel innovation to stabilize,
#   - then blend to full 100% over a short interval.
#
# After state FULL is reached, this logic never activates again.
#
COLD_START_SPEED_THRESHOLD = 0.50    # [m/s]

LAUNCH_FAST_DIVISOR = 1.15
LAUNCH_MIN_TIME = 1.00               # [s]
LAUNCH_RELEASE_SPEED = 5.00          # [m/s]

# At full speed the long corridor is genuinely weakly observable in the
# longitudinal direction, so PF sigma can correctly be 0.30-0.40 m there.
# Do NOT block launch release on PF sigma <= 0.20 m.
#
# We require PF to be FRESH, but launch release is based on odometry
# consistency because wheel spin is the startup-specific failure mechanism.
LAUNCH_WHEEL_INNOVATION_MAX = 0.55   # [m/s]
LAUNCH_STABLE_TIME = 0.12            # [s]

LAUNCH_BLEND_TIME = 0.40             # [s] 1.15 -> 1.00
LAUNCH_THROTTLE_RAMP_TIME = 0.75     # [s]

PF_STALE_TIMEOUT = 0.20              # [s]

# If speed is already high and wheel innovation has settled, release even
# while the corridor PF covariance remains elongated.
LAUNCH_RELEASE_SPEED = 5.50          # [m/s]

# Smooth curvature-based speed-divisor blend.
CURVATURE_DIVISOR_START = 0.60       # [1/m]
CURVATURE_DIVISOR_FULL = 1.40        # [1/m]
CURVATURE_SPEED_HALF_WINDOW = 2      # +/- waypoints

# Measured simulator throttle relation.
K_FF = 0.04131

# Vehicle geometry.
WHEELBASE = 0.3240
MAX_STEERING_RAD = 0.5236

# -------------------------------------------------------------------------
# STEERING
# -------------------------------------------------------------------------
#
# This is intentionally the same structure as the proven older controller.
# There is NO curvature turn-in gate and NO curvature-based lookahead clamp.
#
STEER_LOOKAHEAD_GAIN = 0.45
STEER_LOOKAHEAD_MIN = 0.70
STEER_LOOKAHEAD_MAX = 2.00

# -------------------------------------------------------------------------
# V5 LEFT-CORNER / S-BEND STABILITY
# -------------------------------------------------------------------------
#
# Use path ARC LENGTH for steering target selection and stop a long
# high-speed lookahead from jumping deeply across an upcoming curvature-sign
# reversal.
#
CURVATURE_SIGN_THRESHOLD = 0.04      # [1/m]

# -------------------------------------------------------------------------
# V5.1 RESIDUAL STEERING-LATENCY LEAD
# -------------------------------------------------------------------------
#
# Keep the repo V5 direction-change behavior as the baseline.
#
# The actuator delay measured in the latest bag is still ~0.11 s; it has NOT
# grown after several laps.  At high speed, however, V5's translational pose
# prediction is capped at 0.35 m:
#
#     full delay distance = speed * 0.115
#
# At 5 m/s:
#     full delay distance ~= 0.575 m
#     predicted distance  = 0.350 m
#     residual            ~= 0.225 m
#
# We compensate only a SMALL fraction of that residual, and ONLY when a
# curvature-sign reversal is already inside the steering lookahead.
#
# This advances the S-turn reversal by only ~5-8 cm at racing speed instead
# of adding extra steering magnitude or stacking wall/heading/grip feedback.
#
DIRECTION_CHANGE_PREVIEW_BASE = 0.35      # [m]
LATENCY_REVERSAL_LEAD_GAIN = 0.35
LATENCY_REVERSAL_LEAD_MAX = 0.10          # [m]
DIRECTION_CHANGE_PREVIEW_MAX = 0.45       # [m]

DIRECTION_CHANGE_SEARCH_EXTRA = 0.75      # [m]

# The uploaded bag shows ~0.11-0.13 s actuator lag in the sharp left corner.
# Keep the desired command from outrunning the measured actuator by too much.
# This value is normalized steering units.
STEERING_TRACKING_ERROR_MAX = 0.75

# Normalized command units per second.
# At 50 Hz this allows about 0.10 command change per controller tick.
STEERING_COMMAND_RATE_LIMIT = 5.0

# Measured steering actuator delay.
STEERING_LATENCY_COMP = 0.115       # [s]

# Keep the prediction geometrically bounded.
#
# The no-turn-gate offline replay with this cap matched the older IPS-based
# steering very closely, so do not change it in the same experiment.
MAX_STEERING_PREDICTION_DISTANCE = 0.35   # [m]

# -------------------------------------------------------------------------
# SPEED PROFILE PREVIEW
# -------------------------------------------------------------------------
#
# Deceleration preview stays short so the vehicle does not activate a slow
# hairpin profile too far upstream.
#
# Acceleration preview stays longer so feedforward throttle returns early.
#
SPEED_PREVIEW_BASE = 0.15           # [m]
SPEED_PREVIEW_MIN = 0.35            # [m]

SPEED_DECEL_PREVIEW_TIME = 0.22     # [s]
SPEED_DECEL_PREVIEW_MAX = 2.20      # [m]

SPEED_ACCEL_PREVIEW_TIME = 0.42     # [s]
SPEED_ACCEL_PREVIEW_MAX = 3.30      # [m]

SPEED_TREND_EPS = 0.05              # [m/s]

# -------------------------------------------------------------------------
# 100% OVERSPEED / CORNER-EXIT GUARD
# -------------------------------------------------------------------------
#
# The logged failure showed:
#
#   v=5.65, target=4.23, mode=ACCEL
#   v=6.93, target=5.17, mode=ACCEL
#
# The long acceleration preview was reopening throttle because the CSV profile
# rises farther ahead, even though the REAL current vehicle speed was still
# well above that future target.
#
# This is NOT a PID.  It is a state-machine safety condition for feedforward:
# do not re-enable acceleration until actual speed has caught the profile.
#
ACCEL_PERMISSION_MARGIN = 0.20       # [m/s]

# IMPORTANT:
# Do NOT multiply throttle toward zero because of overspeed.
#
# The final bag proved that a ~5% throttle scale can collapse driven-wheel
# speed almost to zero while chassis speed remains 3-4 m/s.  That creates a
# false wheel-odometry measurement and destabilizes the entire estimator.
#
# Overspeed is therefore handled by MODE SELECTION only:
#
#   - ACCEL is blocked while actual speed is already above the future target.
#   - COAST/HOLD use the local CSV feedforward target normally.
#
# This restores the throttle behavior of the earlier stable 100% run.

# Offset lookahead.
# With IPS, 0.05 m was enough.  With our legal localization stack the
# position error + high-speed CTE can exceed 5 cm, which previously disabled
# the anti-cutting offset exactly when it was needed most.
ALPHA_MAX = 0.20
BETA_MAX = 0.90
MAX_OFFSET_DIST = 0.45

# -------------------------------------------------------------------------
# HIGH-SPEED INSIDE-CORNER GUARD
# -------------------------------------------------------------------------
#
# Uses ONLY our legal localization estimate + the CSV path.
#
# If the vehicle is drifting toward the INSIDE of a bend:
#   1) keep the offset target pushed slightly outward;
#   2) reduce only the virtual latency-prediction distance.
#
# We DO NOT globally change the proven 0.45*v steering-lookahead law.
CUT_GUARD_START = 0.04              # [m] begin intervention
CUT_GUARD_FULL = 0.16               # [m] full intervention

CUT_GUARD_OUTWARD_GAIN = 0.60       # target shift per metre of inside error
CUT_GUARD_OUTWARD_MAX = 0.12        # [m]

# Normal straight-line latency prediction remains 0.35 m.
# When already cutting inside a bend, reduce it smoothly toward 0.20 m.
CUT_GUARD_PREDICTION_MIN = 0.20     # [m]

# Ignore tiny curvature/noise when determining inside/outside.
CUT_GUARD_MIN_CURVATURE = 0.03      # [1/m]

# Local path association.
#
# Never globally re-associate the vehicle to every waypoint while racing.
# Nearby/parallel track segments can otherwise steal the nearest-point match.
NEAREST_SEARCH_BEHIND = 12
NEAREST_SEARCH_AHEAD = 90

# Logging.
LOG_EVERY_N = 25                    # 2 Hz at 50-Hz control

# Custom debug topics are OUR OWN topics, not competition framework inputs.
# Leave disabled for timed racing.
ENABLE_DEBUG_TOPICS = False


# =============================================================================
# TRACK
# =============================================================================

PATH_FILE = '/home/autodrive_devkit/src/f1tenth_control/approved_2.csv'

path_data = pd.read_csv(
    PATH_FILE,
    header=None,
    names=[
        'positions_X',
        'positions_y',
        'Velocity'
    ]
)

goal = path_data[
    ['positions_X', 'positions_y']
].to_numpy(dtype=float)

vel_profile = path_data[
    'Velocity'
].to_numpy(dtype=float)

path_len = len(goal)


# =============================================================================
# PATH PRECOMPUTATION
# =============================================================================

def compute_path_curvature(path_xy):

    n = len(path_xy)
    curvature = np.zeros(n, dtype=float)

    for i in range(n):

        p_prev = path_xy[(i - 1) % n]
        p_curr = path_xy[i]
        p_next = path_xy[(i + 1) % n]

        a = np.linalg.norm(
            p_curr - p_prev
        )

        b = np.linalg.norm(
            p_next - p_curr
        )

        c = np.linalg.norm(
            p_next - p_prev
        )

        cross_z = (
            (p_curr[0] - p_prev[0])
            *
            (p_next[1] - p_prev[1])
            -
            (p_curr[1] - p_prev[1])
            *
            (p_next[0] - p_prev[0])
        )

        area = 0.5 * abs(
            cross_z
        )

        denominator = (
            a * b * c
        )

        curvature[i] = (
            4.0 * area / denominator
            if denominator > 1e-9
            else 0.0
        )

    return curvature


path_curvature = compute_path_curvature(
    goal
)


def compute_signed_path_curvature(path_xy):
    """
    Signed planar curvature.

    Positive: left-hand bend.
    Negative: right-hand bend.
    """

    n = len(path_xy)
    curvature = np.zeros(n, dtype=float)

    for i in range(n):

        p_prev = path_xy[(i - 1) % n]
        p_curr = path_xy[i]
        p_next = path_xy[(i + 1) % n]

        a = np.linalg.norm(
            p_curr - p_prev
        )

        b = np.linalg.norm(
            p_next - p_curr
        )

        c = np.linalg.norm(
            p_next - p_prev
        )

        cross_z = (
            (p_curr[0] - p_prev[0])
            *
            (p_next[1] - p_prev[1])
            -
            (p_curr[1] - p_prev[1])
            *
            (p_next[0] - p_prev[0])
        )

        denominator = (
            a * b * c
        )

        curvature[i] = (
            2.0 * cross_z / denominator
            if denominator > 1e-9
            else 0.0
        )

    return curvature


path_signed_curvature = compute_signed_path_curvature(
    goal
)


# =============================================================================
# MATH HELPERS
# =============================================================================

def wrap_angle(angle):

    return math.atan2(
        math.sin(angle),
        math.cos(angle)
    )


def quaternion_to_yaw(q):

    siny_cosp = 2.0 * (
        q.w * q.z
        +
        q.x * q.y
    )

    cosy_cosp = 1.0 - 2.0 * (
        q.y * q.y
        +
        q.z * q.z
    )

    return math.atan2(
        siny_cosp,
        cosy_cosp
    )


# =============================================================================
# PATH INDEX HELPERS
# =============================================================================

def wrapped_indices(
    center_idx,
    behind,
    ahead
):

    return np.array([
        (center_idx + offset) % path_len
        for offset in range(
            -behind,
            ahead + 1
        )
    ], dtype=int)


def update_nearest_path_index(
    position,
    previous_idx
):
    """
    Find the nearest waypoint only on the local racing-line branch.

    This is intentionally monotonic/local rather than a full-path global
    nearest-point search.
    """

    indices = wrapped_indices(
        previous_idx,
        NEAREST_SEARCH_BEHIND,
        NEAREST_SEARCH_AHEAD
    )

    points = goal[
        indices
    ]

    distances = np.linalg.norm(
        points - position,
        axis=1
    )

    return int(
        indices[
            int(
                np.argmin(
                    distances
                )
            )
        ]
    )


def advance_path_index_by_distance(
    start_idx,
    distance_m
):
    """
    Walk forward along path ARC LENGTH.
    """

    idx = int(
        start_idx
    ) % path_len

    travelled = 0.0

    for _ in range(path_len):

        if travelled >= distance_m:
            break

        next_idx = (
            idx + 1
        ) % path_len

        travelled += float(
            np.linalg.norm(
                goal[next_idx]
                -
                goal[idx]
            )
        )

        idx = next_idx

    return idx


def find_steering_lookahead_index(
    start_idx,
    position,
    desired_distance
):
    """
    Search FORWARD on the current branch and return the first waypoint whose
    Euclidean distance from the steering pose reaches the requested lookahead.

    This reproduces the useful geometry of the team's older successful
    controller without using IPS.
    """

    idx = int(
        start_idx
    ) % path_len

    for _ in range(path_len):

        distance = np.linalg.norm(
            goal[idx]
            -
            position
        )

        if distance >= desired_distance:
            return idx

        idx = (
            idx + 1
        ) % path_len

    return idx


# =============================================================================
# V5 STEERING ARC-LENGTH / DIRECTION-CHANGE HELPERS
# =============================================================================

def first_curvature_sign_change_distance(
    start_idx,
    max_distance
):
    """
    Return the path arc distance to the first meaningful curvature-sign
    reversal ahead.

    Tiny near-zero curvature is ignored to avoid numerical sign flicker.
    """

    idx = int(
        start_idx
    ) % path_len

    current_sign = 0

    # Find the current meaningful bend direction.
    for offset in range(8):

        kappa = float(
            path_signed_curvature[
                (idx + offset) % path_len
            ]
        )

        if abs(
            kappa
        ) >= CURVATURE_SIGN_THRESHOLD:

            current_sign = (
                1
                if kappa > 0.0
                else -1
            )

            break

    if current_sign == 0:
        return None, None

    travelled = 0.0

    for _ in range(path_len):

        next_idx = (
            idx + 1
        ) % path_len

        travelled += float(
            np.linalg.norm(
                goal[next_idx]
                -
                goal[idx]
            )
        )

        idx = next_idx

        kappa = float(
            path_signed_curvature[
                idx
            ]
        )

        if abs(
            kappa
        ) >= CURVATURE_SIGN_THRESHOLD:

            sign_here = (
                1
                if kappa > 0.0
                else -1
            )

            if sign_here != current_sign:

                return (
                    travelled,
                    idx
                )

        if travelled > max_distance:
            break

    return None, None


def steering_lookahead_index_by_arc_length(
    start_idx,
    distance_m
):
    """
    Select steering target by FORWARD PATH ARC LENGTH.

    This prevents a hairpin/chicane from making the target jump to a nearby
    but topologically distant branch of the path.
    """

    return advance_path_index_by_distance(
        start_idx,
        distance_m
    )


# =============================================================================
# CURVATURE-DEPENDENT SPEED SCALING
# =============================================================================

def speed_curvature_at_index(
    index
):
    """
    Robust local curvature around one future speed-profile waypoint.
    """

    idx = int(
        index
    ) % path_len

    max_curvature = 0.0

    for offset in range(
        -CURVATURE_SPEED_HALF_WINDOW,
        CURVATURE_SPEED_HALF_WINDOW + 1
    ):

        kappa = abs(
            float(
                path_curvature[
                    (idx + offset) % path_len
                ]
            )
        )

        if kappa > max_curvature:
            max_curvature = kappa

    return max_curvature


def curvature_speed_divisor(
    curvature,
    fast_divisor=VELOCITY_DIVISOR
):
    """
    Straight/gentle:
        divisor = 1.15

    Extreme/tight:
        divisor = 1.50

    Smooth interpolation between them.
    """

    denominator = (
        CURVATURE_DIVISOR_FULL
        -
        CURVATURE_DIVISOR_START
    )

    if denominator <= 1e-9:
        return TIGHT_CORNER_DIVISOR

    blend = np.clip(
        (
            curvature
            -
            CURVATURE_DIVISOR_START
        )
        /
        denominator,
        0.0,
        1.0
    )

    return float(
        fast_divisor
        +
        blend
        *
        (
            TIGHT_CORNER_DIVISOR
            -
            fast_divisor
        )
    )


# =============================================================================
# INSIDE-CORNER GEOMETRY
# =============================================================================

def signed_cross_track_error(
    position,
    nearest_idx
):
    """
    Signed lateral distance from the local racing-line tangent.

    Positive = vehicle is left of the path tangent.
    Negative = vehicle is right of the path tangent.
    """

    previous_idx = (
        nearest_idx - 1
    ) % path_len

    next_idx = (
        nearest_idx + 1
    ) % path_len

    tangent = (
        goal[next_idx]
        -
        goal[previous_idx]
    )

    tangent_norm = float(
        np.linalg.norm(
            tangent
        )
    )

    if tangent_norm < 1e-9:
        return 0.0

    tangent = (
        tangent
        /
        tangent_norm
    )

    error_vector = (
        position
        -
        goal[
            nearest_idx
        ]
    )

    return float(
        tangent[0]
        *
        error_vector[1]
        -
        tangent[1]
        *
        error_vector[0]
    )


def inside_corner_error(
    position,
    nearest_idx
):
    """
    Return only the component that means the vehicle is cutting toward the
    INSIDE of the current bend.

    For a left bend:
        left-of-path error is inside.

    For a right bend:
        right-of-path error is inside.
    """

    kappa = float(
        path_signed_curvature[
            nearest_idx
        ]
    )

    if abs(
        kappa
    ) < CUT_GUARD_MIN_CURVATURE:

        return 0.0

    cross_track = (
        signed_cross_track_error(
            position,
            nearest_idx
        )
    )

    inside = (
        cross_track
        *
        (
            1.0
            if kappa > 0.0
            else -1.0
        )
    )

    return max(
        0.0,
        float(
            inside
        )
    )


def outward_path_normal(
    nearest_idx
):
    """
    Unit normal pointing OUTSIDE the current bend.
    """

    previous_idx = (
        nearest_idx - 1
    ) % path_len

    next_idx = (
        nearest_idx + 1
    ) % path_len

    tangent = (
        goal[next_idx]
        -
        goal[previous_idx]
    )

    tangent_norm = float(
        np.linalg.norm(
            tangent
        )
    )

    if tangent_norm < 1e-9:

        return np.zeros(
            2,
            dtype=float
        )

    tangent = (
        tangent
        /
        tangent_norm
    )

    left_normal = np.array([
        -tangent[1],
        tangent[0]
    ])

    kappa = float(
        path_signed_curvature[
            nearest_idx
        ]
    )

    if kappa > 0.0:

        # Left turn -> outside is right.
        return (
            -left_normal
        )

    if kappa < 0.0:

        # Right turn -> outside is left.
        return (
            left_normal
        )

    return np.zeros(
        2,
        dtype=float
    )


# =============================================================================
# STEERING LATENCY PREDICTION
# =============================================================================

def predict_control_pose(
    position,
    yaw,
    speed,
    yaw_rate,
    prediction_distance_cap
):
    """
    Predict ONLY the steering pose.

    Speed-profile indexing always stays tied to the current global
    localization position.

    The measured actuator time delay is used, but the geometric prediction is
    capped because the offline /1.15 replay showed that removing the turn-in
    gate while retaining this cap closely reproduces the older IPS controller.
    """

    if speed <= 1e-6:

        return (
            position.copy(),
            yaw,
            0.0
        )

    prediction_time = (
        STEERING_LATENCY_COMP
    )

    prediction_time = min(
        prediction_time,
        prediction_distance_cap
        /
        max(
            abs(speed),
            1e-6
        )
    )

    prediction_distance = (
        abs(speed)
        *
        prediction_time
    )

    if abs(
        yaw_rate
    ) < 1e-4:

        predicted_position = np.array([
            position[0]
            +
            speed
            *
            prediction_time
            *
            math.cos(yaw),

            position[1]
            +
            speed
            *
            prediction_time
            *
            math.sin(yaw)
        ])

        return (
            predicted_position,
            yaw,
            prediction_distance
        )

    predicted_yaw = wrap_angle(
        yaw
        +
        yaw_rate
        *
        prediction_time
    )

    radius = (
        speed
        /
        yaw_rate
    )

    predicted_position = np.array([
        position[0]
        +
        radius
        *
        (
            math.sin(
                predicted_yaw
            )
            -
            math.sin(
                yaw
            )
        ),

        position[1]
        -
        radius
        *
        (
            math.cos(
                predicted_yaw
            )
            -
            math.cos(
                yaw
            )
        )
    ])

    return (
        predicted_position,
        predicted_yaw,
        prediction_distance
    )


# =============================================================================
# PURE PURSUIT
# =============================================================================

def transform_world_to_vehicle(
    vehicle_position,
    target_point,
    vehicle_yaw
):

    c = math.cos(
        vehicle_yaw
    )

    s = math.sin(
        vehicle_yaw
    )

    rotation = np.array([
        [c, s],
        [-s, c]
    ])

    return (
        rotation
        @
        (
            target_point
            -
            vehicle_position
        )
    )


def pure_pursuit_curvature(
    point_car_frame
):

    x = float(
        point_car_frame[0]
    )

    y = float(
        point_car_frame[1]
    )

    distance = math.hypot(
        x,
        y
    )

    if distance < 1e-6:
        return 0.0

    return (
        2.0
        *
        y
        /
        (
            distance
            *
            distance
        )
    )


def compute_offset_lookahead(
    position,
    nearest_idx,
    destination_idx
):
    """
    Offset the Pure Pursuit target outward only when the local path geometry
    calls for it.

    This is retained from the previously successful control family.
    """

    pw = goal[
        nearest_idx
    ]

    pd = goal[
        destination_idx
    ]

    vector_wd = (
        pd - pw
    )

    len_wd = float(
        np.linalg.norm(
            vector_wd
        )
    )

    theta_pwd = math.atan2(
        vector_wd[1],
        vector_wd[0]
    )

    previous_idx = (
        nearest_idx - 1
    ) % path_len

    next_idx = (
        nearest_idx + 1
    ) % path_len

    tangent = (
        goal[next_idx]
        -
        goal[previous_idx]
    )

    theta_path = math.atan2(
        tangent[1],
        tangent[0]
    )

    theta = wrap_angle(
        theta_path
        -
        theta_pwd
    )

    distance_vehicle_to_pw = float(
        np.linalg.norm(
            position
            -
            pw
        )
    )

    alpha = min(
        distance_vehicle_to_pw
        /
        ALPHA_MAX,
        1.0
    )

    curvature_here = float(
        path_curvature[
            nearest_idx
        ]
    )

    curvature_destination = float(
        path_curvature[
            destination_idx
        ]
    )

    if curvature_here >= curvature_destination:

        beta = 0.0

    elif (
        curvature_destination
        -
        curvature_here
    ) < BETA_MAX:

        beta = (
            curvature_destination
            -
            curvature_here
        ) / BETA_MAX

    else:

        beta = 1.0

    tau = (
        1.0
        -
        alpha
    ) * beta

    offset_distance = min(
        len_wd
        *
        math.tan(
            abs(theta)
        ),
        MAX_OFFSET_DIST
    )

    direction = (
        1.0
        if theta >= 0.0
        else -1.0
    )

    offset_angle = (
        theta_pwd
        +
        direction
        *
        math.pi
        /
        2.0
    )

    return np.array([
        pd[0]
        +
        tau
        *
        offset_distance
        *
        math.cos(
            offset_angle
        ),

        pd[1]
        +
        tau
        *
        offset_distance
        *
        math.sin(
            offset_angle
        )
    ])


# =============================================================================
# FEEDFORWARD THROTTLE
# =============================================================================

def speed_control(
    target_speed
):

    return float(
        np.clip(
            K_FF
            *
            target_speed,
            0.0,
            1.0
        )
    )


# =============================================================================
# CONTROLLER NODE
# =============================================================================

class RoboRacerController(Node):

    def __init__(self):

        super().__init__(
            'pps_icra_2026'
        )

        # ------------------------------------------------------------------
        # State
        # ------------------------------------------------------------------

        self.localization_position = np.array(
            [0.8, 3.16],
            dtype=float
        )

        self.control_speed = 0.0

        self.car_yaw = 0.0
        self.car_yaw_rate = 0.0

        # Allowed measured steering input.
        self.measured_steering_rad = 0.0
        self.measured_steering_received = False

        # Final command state for actuator-aware slew limiting.
        self.last_steering_command = 0.0
        self.last_steering_command_time = None

        self.localization_received = False
        self.speed_received = False
        self.imu_received = False

        # Cold-start estimator-health inputs.
        self.pf_received = False
        self.pf_sigma_max = float('inf')
        self.last_pf_receive_time = None

        self.wheel_innovation_received = False
        self.wheel_innovation = float('inf')

        # Launch-state machine:
        #   UNINITIALIZED -> SAFE -> BLEND -> FULL
        self.launch_state = 'UNINITIALIZED'
        self.launch_start_time = None
        self.launch_stable_start_time = None
        self.launch_blend_start_time = None

        self.control_counter = 0

        initial_distances = np.linalg.norm(
            goal
            -
            self.localization_position,
            axis=1
        )

        self.nearest_path_idx = int(
            np.argmin(
                initial_distances
            )
        )

        self.lookahead_idx = (
            self.nearest_path_idx
        )

        self.speed_idx = (
            self.nearest_path_idx
        )

        # ------------------------------------------------------------------
        # LEGAL / INTERNAL subscriptions only
        # ------------------------------------------------------------------

        # Internal global localization produced by our permitted-sensor stack.
        self.localization_sub = self.create_subscription(
            Odometry,
            '/localization/odom',
            self.localization_callback,
            20
        )

        # Internal EKF speed produced by our permitted-sensor stack.
        self.speed_sub = self.create_subscription(
            Odometry,
            '/odometry/filtered',
            self.speed_callback,
            20
        )

        # Competition-permitted sensor.
        self.imu_sub = self.create_subscription(
            Imu,
            '/autodrive/roboracer_1/imu',
            self.imu_callback,
            20
        )

        # Competition-permitted measured steering sensor.
        self.measured_steering_sub = self.create_subscription(
            Float32,
            '/autodrive/roboracer_1/steering',
            self.measured_steering_callback,
            20
        )

        # Internal estimator-health topics derived only from permitted sensors.
        self.pf_sub = self.create_subscription(
            Odometry,
            '/pf/pose/odom',
            self.pf_callback,
            20
        )

        self.wheel_innovation_sub = self.create_subscription(
            Float32,
            '/roboracer/odom_debug/wheel_innovation',
            self.wheel_innovation_callback,
            20
        )

        # ------------------------------------------------------------------
        # Outputs
        # ------------------------------------------------------------------

        self.steering_pub = self.create_publisher(
            Float32,
            '/autodrive/roboracer_1/steering_command',
            10
        )

        self.throttle_pub = self.create_publisher(
            Float32,
            '/autodrive/roboracer_1/throttle_command',
            10
        )

        # ------------------------------------------------------------------
        # Optional OUR-OWN debug publishers
        # ------------------------------------------------------------------

        self.debug_publishers = {}

        if ENABLE_DEBUG_TOPICS:

            self.debug_publishers = {
                'nearest_idx':
                    self.create_publisher(
                        Int32,
                        '/controller_debug/nearest_idx',
                        10
                    ),

                'lookahead_idx':
                    self.create_publisher(
                        Int32,
                        '/controller_debug/lookahead_idx',
                        10
                    ),

                'lookahead':
                    self.create_publisher(
                        Float32,
                        '/controller_debug/steering_lookahead',
                        10
                    ),

                'target_speed':
                    self.create_publisher(
                        Float32,
                        '/controller_debug/target_speed',
                        10
                    ),

                'effective_divisor':
                    self.create_publisher(
                        Float32,
                        '/controller_debug/effective_divisor',
                        10
                    ),

                'prediction_distance':
                    self.create_publisher(
                        Float32,
                        '/controller_debug/prediction_distance',
                        10
                    ),

                'target_point':
                    self.create_publisher(
                        Point,
                        '/controller_debug/target_point',
                        10
                    ),
            }

        # ------------------------------------------------------------------
        # 50-Hz controller
        # ------------------------------------------------------------------

        self.timer = self.create_timer(
            CONTROL_PERIOD,
            self.control_loop
        )

        self.get_logger().info(
            'RoboRacer 100% REPO-BASE LATENCY-V5.1 controller started | '
            f'control={1.0 / CONTROL_PERIOD:.1f} Hz | '
            f'fast_div={VELOCITY_DIVISOR:.2f} | '
            f'tight_div={TIGHT_CORNER_DIVISOR:.2f} | '
            f'steer_L=clip({STEER_LOOKAHEAD_GAIN:.2f}*v, '
            f'{STEER_LOOKAHEAD_MIN:.2f}, '
            f'{STEER_LOOKAHEAD_MAX:.2f}) | '
            f'latency={STEERING_LATENCY_COMP:.3f}s | '
            f'alpha_max={ALPHA_MAX:.2f}m | '
            f'cut_guard={CUT_GUARD_START:.2f}->{CUT_GUARD_FULL:.2f}m | '
            'turn_in_gate=DISABLED'
        )

    # =========================================================================
    # CALLBACKS
    # =========================================================================

    def localization_callback(
        self,
        msg: Odometry
    ):

        self.localization_position[0] = float(
            msg.pose.pose.position.x
        )

        self.localization_position[1] = float(
            msg.pose.pose.position.y
        )

        self.localization_received = True

    def speed_callback(
        self,
        msg: Odometry
    ):

        vx = float(
            msg.twist.twist.linear.x
        )

        vy = float(
            msg.twist.twist.linear.y
        )

        self.control_speed = math.hypot(
            vx,
            vy
        )

        self.speed_received = True

    def imu_callback(
        self,
        msg: Imu
    ):

        self.car_yaw = quaternion_to_yaw(
            msg.orientation
        )

        self.car_yaw_rate = float(
            msg.angular_velocity.z
        )

        self.imu_received = True

    def measured_steering_callback(
        self,
        msg: Float32
    ):

        self.measured_steering_rad = float(
            msg.data
        )

        self.measured_steering_received = True

    def pf_callback(
        self,
        msg: Odometry
    ):
        """
        Read only PF covariance/health.  PF position is NOT used directly by
        the controller; control position remains /localization/odom.
        """

        covariance = np.asarray(
            msg.pose.covariance,
            dtype=float
        )

        covariance_xy = np.array([
            [
                covariance[0],
                covariance[1]
            ],
            [
                covariance[6],
                covariance[7]
            ]
        ], dtype=float)

        covariance_xy = 0.5 * (
            covariance_xy
            +
            covariance_xy.T
        )

        eigenvalues = np.linalg.eigvalsh(
            covariance_xy
        )

        eigenvalues = np.maximum(
            eigenvalues,
            0.0
        )

        self.pf_sigma_max = float(
            np.sqrt(
                np.max(
                    eigenvalues
                )
            )
        )

        self.pf_received = True
        self.last_pf_receive_time = (
            self.get_clock().now()
        )

    def wheel_innovation_callback(
        self,
        msg: Float32
    ):

        self.wheel_innovation = float(
            msg.data
        )

        self.wheel_innovation_received = True

    # =========================================================================
    # COLD START MANAGER
    # =========================================================================

    def update_launch_manager(
        self,
        current_speed
    ):
        """
        Returns:
            fast_divisor
            throttle_scale

        The steady-state FULL mode is exactly the proven 100% controller.
        """

        now = self.get_clock().now()

        # --------------------------------------------------------------
        # Decide once whether this is a cold standing start.
        # --------------------------------------------------------------

        if self.launch_state == 'UNINITIALIZED':

            if current_speed <= COLD_START_SPEED_THRESHOLD:

                self.launch_state = 'SAFE'
                self.launch_start_time = now
                self.launch_stable_start_time = None

                self.get_logger().info(
                    'Cold standing start detected: '
                    'temporary /1.15 launch protection enabled.'
                )

            else:

                self.launch_state = 'FULL'

                self.get_logger().info(
                    'Controller started while moving: '
                    'using full 100% racing mode immediately.'
                )

        # --------------------------------------------------------------
        # Full racing mode.
        # --------------------------------------------------------------

        if self.launch_state == 'FULL':

            return (
                VELOCITY_DIVISOR,
                1.0
            )

        # --------------------------------------------------------------
        # Blend from safe launch to full 100%.
        # --------------------------------------------------------------

        if self.launch_state == 'BLEND':

            elapsed_blend = (
                now
                -
                self.launch_blend_start_time
            ).nanoseconds * 1e-9

            blend = float(
                np.clip(
                    elapsed_blend
                    /
                    max(
                        LAUNCH_BLEND_TIME,
                        1e-6
                    ),
                    0.0,
                    1.0
                )
            )

            fast_divisor = (
                LAUNCH_FAST_DIVISOR
                +
                blend
                *
                (
                    VELOCITY_DIVISOR
                    -
                    LAUNCH_FAST_DIVISOR
                )
            )

            if blend >= 1.0:

                self.launch_state = 'FULL'

                self.get_logger().info(
                    'Launch estimator stabilized: '
                    '100% racing mode enabled.'
                )

                return (
                    VELOCITY_DIVISOR,
                    1.0
                )

            return (
                fast_divisor,
                1.0
            )

        # --------------------------------------------------------------
        # SAFE standing-launch mode.
        # --------------------------------------------------------------

        elapsed = (
            now
            -
            self.launch_start_time
        ).nanoseconds * 1e-9

        # Smooth first throttle application to reduce physical wheel spin.
        throttle_scale = float(
            np.clip(
                elapsed
                /
                max(
                    LAUNCH_THROTTLE_RAMP_TIME,
                    1e-6
                ),
                0.0,
                1.0
            )
        )

        pf_fresh = False

        if (
            self.pf_received
            and
            self.last_pf_receive_time is not None
        ):

            pf_age = (
                now
                -
                self.last_pf_receive_time
            ).nanoseconds * 1e-9

            pf_fresh = (
                pf_age
                <=
                PF_STALE_TIMEOUT
            )

        # Corridor PF covariance is allowed to be elongated.
        # For startup release we only require that PF is alive/fresh.
        pf_ok = (
            pf_fresh
        )

        wheel_ok = (
            self.wheel_innovation_received
            and
            abs(
                self.wheel_innovation
            )
            <=
            LAUNCH_WHEEL_INNOVATION_MAX
        )

        speed_ok = (
            current_speed
            >=
            LAUNCH_RELEASE_SPEED
        )

        time_ok = (
            elapsed
            >=
            LAUNCH_MIN_TIME
        )

        stable_now = (
            pf_ok
            and
            wheel_ok
            and
            speed_ok
            and
            time_ok
        )

        if stable_now:

            if self.launch_stable_start_time is None:

                self.launch_stable_start_time = now

            stable_duration = (
                now
                -
                self.launch_stable_start_time
            ).nanoseconds * 1e-9

            if (
                stable_duration
                >=
                LAUNCH_STABLE_TIME
            ):

                self.launch_state = 'BLEND'
                self.launch_blend_start_time = now

                self.get_logger().info(
                    'Cold-start odometry consistency reached with fresh PF: '
                    'blending /1.15 -> 100%.'
                )

        else:

            self.launch_stable_start_time = None

        return (
            LAUNCH_FAST_DIVISOR,
            throttle_scale
        )

    # =========================================================================
    # DEBUG
    # =========================================================================

    def publish_debug(
        self,
        steering_lookahead,
        target_speed,
        effective_divisor,
        prediction_distance,
        target_point
    ):

        if not ENABLE_DEBUG_TOPICS:
            return

        msg_i = Int32()
        msg_i.data = int(
            self.nearest_path_idx
        )
        self.debug_publishers[
            'nearest_idx'
        ].publish(
            msg_i
        )

        msg_i = Int32()
        msg_i.data = int(
            self.lookahead_idx
        )
        self.debug_publishers[
            'lookahead_idx'
        ].publish(
            msg_i
        )

        msg_f = Float32()
        msg_f.data = float(
            steering_lookahead
        )
        self.debug_publishers[
            'lookahead'
        ].publish(
            msg_f
        )

        msg_f = Float32()
        msg_f.data = float(
            target_speed
        )
        self.debug_publishers[
            'target_speed'
        ].publish(
            msg_f
        )

        msg_f = Float32()
        msg_f.data = float(
            effective_divisor
        )
        self.debug_publishers[
            'effective_divisor'
        ].publish(
            msg_f
        )

        msg_f = Float32()
        msg_f.data = float(
            prediction_distance
        )
        self.debug_publishers[
            'prediction_distance'
        ].publish(
            msg_f
        )

        point_msg = Point()

        point_msg.x = float(
            target_point[0]
        )

        point_msg.y = float(
            target_point[1]
        )

        point_msg.z = 0.0

        self.debug_publishers[
            'target_point'
        ].publish(
            point_msg
        )

    # =========================================================================
    # CONTROL
    # =========================================================================

    def control_loop(
        self
    ):

        if not (
            self.localization_received
            and
            self.speed_received
            and
            self.imu_received
        ):

            if (
                self.control_counter
                %
                LOG_EVERY_N
            ) == 0:

                self.get_logger().warn(
                    'Waiting for /localization/odom, '
                    '/odometry/filtered and IMU...'
                )

            self.control_counter += 1
            return

        current_position = (
            self.localization_position.copy()
        )

        current_speed = float(
            self.control_speed
        )

        current_yaw = float(
            self.car_yaw
        )

        current_yaw_rate = float(
            self.car_yaw_rate
        )

        (
            active_fast_divisor,
            launch_throttle_scale
        ) = self.update_launch_manager(
            current_speed
        )

        # ------------------------------------------------------------------
        # Current local path progress.
        # ------------------------------------------------------------------

        self.nearest_path_idx = (
            update_nearest_path_index(
                current_position,
                self.nearest_path_idx
            )
        )

        # ------------------------------------------------------------------
        # STEERING
        #
        # Predict only enough to compensate the measured actuator latency.
        # NO turn-in gate.
        # NO curvature lookahead cap.
        # ------------------------------------------------------------------

        # --------------------------------------------------------------
        # Detect whether the CURRENT legal localization pose is already
        # cutting toward the inside of this bend.
        # --------------------------------------------------------------

        inside_error = inside_corner_error(
            current_position,
            self.nearest_path_idx
        )

        guard_denominator = max(
            CUT_GUARD_FULL
            -
            CUT_GUARD_START,
            1e-6
        )

        cut_guard_blend = float(
            np.clip(
                (
                    inside_error
                    -
                    CUT_GUARD_START
                )
                /
                guard_denominator,
                0.0,
                1.0
            )
        )

        # Full measured-delay prediction on a healthy line.
        # Reduce ONLY the geometric prediction distance when the controller
        # can already see that the vehicle is cutting inside.
        prediction_distance_cap = (
            MAX_STEERING_PREDICTION_DISTANCE
            +
            cut_guard_blend
            *
            (
                CUT_GUARD_PREDICTION_MIN
                -
                MAX_STEERING_PREDICTION_DISTANCE
            )
        )

        (
            steering_position,
            steering_yaw,
            prediction_distance
        ) = predict_control_pose(
            current_position,
            current_yaw,
            current_speed,
            current_yaw_rate,
            prediction_distance_cap
        )

        steering_nearest_idx = (
            update_nearest_path_index(
                steering_position,
                self.nearest_path_idx
            )
        )

        # Proven lookahead law remains the sole lookahead rule.
        base_steering_lookahead = float(
            np.clip(
                STEER_LOOKAHEAD_GAIN
                *
                current_speed,
                STEER_LOOKAHEAD_MIN,
                STEER_LOOKAHEAD_MAX
            )
        )

        # --------------------------------------------------------------
        # V5 S-BEND / HAIRPIN DIRECTION-CHANGE GUARD
        #
        # Keep the proven dynamic lookahead, but if an opposite-curvature
        # section lies inside that lookahead, do not target deeply through
        # the whole hairpin.  Allow only a modest 0.35 m preview past the
        # reversal.
        # --------------------------------------------------------------

        (
            direction_change_distance,
            direction_change_idx
        ) = first_curvature_sign_change_distance(
            steering_nearest_idx,
            base_steering_lookahead
            +
            DIRECTION_CHANGE_SEARCH_EXTRA
        )

        direction_change_active = False

        steering_lookahead = (
            base_steering_lookahead
        )

        # --------------------------------------------------------------
        # V5.1 RESIDUAL LATENCY COMPENSATION
        #
        # predict_control_pose() already compensates actuator latency, but
        # translation is capped at MAX_STEERING_PREDICTION_DISTANCE.
        #
        # The residual distance is the part of speed*delay that was NOT
        # represented by that bounded pose prediction.
        #
        # Use only 35% of that residual and cap it at 10 cm.  This is a
        # phase-lead adjustment, NOT an increase in steering authority.
        # --------------------------------------------------------------

        full_latency_distance = (
            abs(
                current_speed
            )
            *
            STEERING_LATENCY_COMP
        )

        residual_latency_distance = max(
            0.0,
            full_latency_distance
            -
            prediction_distance
        )

        latency_reversal_lead = min(
            LATENCY_REVERSAL_LEAD_MAX,
            LATENCY_REVERSAL_LEAD_GAIN
            *
            residual_latency_distance
        )

        direction_change_preview = min(
            DIRECTION_CHANGE_PREVIEW_MAX,
            DIRECTION_CHANGE_PREVIEW_BASE
            +
            latency_reversal_lead
        )

        if (
            direction_change_distance is not None
            and
            direction_change_distance
            <
            base_steering_lookahead
        ):

            steering_lookahead = max(
                STEER_LOOKAHEAD_MIN,
                min(
                    base_steering_lookahead,
                    direction_change_distance
                    +
                    direction_change_preview
                )
            )

            direction_change_active = True

        self.lookahead_idx = (
            steering_lookahead_index_by_arc_length(
                steering_nearest_idx,
                steering_lookahead
            )
        )

        offset_target = (
            compute_offset_lookahead(
                steering_position,
                steering_nearest_idx,
                self.lookahead_idx
            )
        )

        # --------------------------------------------------------------
        # High-speed anti-cutting correction.
        #
        # If the legal localization estimate says we are already inside the
        # racing line, move the PP target slightly OUTWARD.  This changes the
        # geometry directly instead of blindly scaling steering.
        # --------------------------------------------------------------

        outward_shift = float(
            np.clip(
                CUT_GUARD_OUTWARD_GAIN
                *
                max(
                    0.0,
                    inside_error
                    -
                    CUT_GUARD_START
                ),
                0.0,
                CUT_GUARD_OUTWARD_MAX
            )
        )

        if outward_shift > 0.0:

            offset_target = (
                offset_target
                +
                outward_path_normal(
                    self.nearest_path_idx
                )
                *
                outward_shift
            )

        point_car_frame = (
            transform_world_to_vehicle(
                steering_position,
                offset_target,
                steering_yaw
            )
        )

        curvature_command = (
            pure_pursuit_curvature(
                point_car_frame
            )
        )

        steering_angle = math.atan(
            WHEELBASE
            *
            curvature_command
        )

        raw_normalized_steering = float(
            np.clip(
                steering_angle
                /
                MAX_STEERING_RAD,
                -1.0,
                1.0
            )
        )

        # --------------------------------------------------------------
        # V5 ACTUATOR-AWARE STABILIZER
        #
        # The failing bag shows the desired command changing from roughly
        # +0.7 -> -1.0 -> +1.0 while the physical steering is still carrying
        # the previous sign.  Limit how far the command can lead the measured
        # actuator, then apply a mild command slew limit.
        # --------------------------------------------------------------

        actuator_aware_steering = (
            raw_normalized_steering
        )

        if self.measured_steering_received:

            measured_normalized_steering = float(
                np.clip(
                    self.measured_steering_rad
                    /
                    MAX_STEERING_RAD,
                    -1.0,
                    1.0
                )
            )

            actuator_aware_steering = float(
                np.clip(
                    raw_normalized_steering,
                    measured_normalized_steering
                    -
                    STEERING_TRACKING_ERROR_MAX,
                    measured_normalized_steering
                    +
                    STEERING_TRACKING_ERROR_MAX
                )
            )

        else:

            measured_normalized_steering = 0.0

        steering_now = self.get_clock().now()

        if self.last_steering_command_time is None:

            steering_dt = CONTROL_PERIOD

        else:

            steering_dt = (
                steering_now
                -
                self.last_steering_command_time
            ).nanoseconds * 1e-9

            steering_dt = float(
                np.clip(
                    steering_dt,
                    0.005,
                    0.050
                )
            )

        max_command_delta = (
            STEERING_COMMAND_RATE_LIMIT
            *
            steering_dt
        )

        normalized_steering = float(
            np.clip(
                actuator_aware_steering,
                self.last_steering_command
                -
                max_command_delta,
                self.last_steering_command
                +
                max_command_delta
            )
        )

        normalized_steering = float(
            np.clip(
                normalized_steering,
                -1.0,
                1.0
            )
        )

        self.last_steering_command = (
            normalized_steering
        )

        self.last_steering_command_time = (
            steering_now
        )

        # ------------------------------------------------------------------
        # SPEED PROFILE
        #
        # Keep the /1.15 fast profile on straight/gentle sections.
        # Tight-corner divisor remains 1.50.
        # ------------------------------------------------------------------

        current_speed_curvature = (
            speed_curvature_at_index(
                self.nearest_path_idx
            )
        )

        current_divisor = (
            curvature_speed_divisor(
                current_speed_curvature,
                active_fast_divisor
            )
        )

        current_profile_velocity = float(
            vel_profile[
                self.nearest_path_idx
            ]
            /
            current_divisor
        )

        # Short preview for deceleration.
        decel_preview_distance = float(
            np.clip(
                SPEED_PREVIEW_BASE
                +
                SPEED_DECEL_PREVIEW_TIME
                *
                current_speed,
                SPEED_PREVIEW_MIN,
                SPEED_DECEL_PREVIEW_MAX
            )
        )

        decel_idx = (
            advance_path_index_by_distance(
                self.nearest_path_idx,
                decel_preview_distance
            )
        )

        decel_curvature = (
            speed_curvature_at_index(
                decel_idx
            )
        )

        decel_divisor = (
            curvature_speed_divisor(
                decel_curvature,
                active_fast_divisor
            )
        )

        decel_target_velocity = float(
            vel_profile[
                decel_idx
            ]
            /
            decel_divisor
        )

        # Longer preview for acceleration.
        accel_preview_distance = float(
            np.clip(
                SPEED_PREVIEW_BASE
                +
                SPEED_ACCEL_PREVIEW_TIME
                *
                current_speed,
                SPEED_PREVIEW_MIN,
                SPEED_ACCEL_PREVIEW_MAX
            )
        )

        accel_idx = (
            advance_path_index_by_distance(
                self.nearest_path_idx,
                accel_preview_distance
            )
        )

        accel_curvature = (
            speed_curvature_at_index(
                accel_idx
            )
        )

        accel_divisor = (
            curvature_speed_divisor(
                accel_curvature,
                active_fast_divisor
            )
        )

        accel_target_velocity = float(
            vel_profile[
                accel_idx
            ]
            /
            accel_divisor
        )

        # ------------------------------------------------------------------
        # ACTUAL-SPEED-AWARE SPEED MODE
        #
        # The acceleration preview is allowed only if the current vehicle
        # speed is not already above the future acceleration target.
        #
        # This prevents:
        #
        #     actual 6.9 m/s
        #     target 5.2 m/s
        #     mode ACCEL
        #
        # which was the direct high-speed corner failure in the log.
        # ------------------------------------------------------------------

        accel_is_permitted = (
            current_speed
            <=
            accel_target_velocity
            +
            ACCEL_PERMISSION_MARGIN
        )

        # Approaching slower profile always has priority.
        if (
            decel_target_velocity
            <
            current_profile_velocity
            -
            SPEED_TREND_EPS
        ):

            speed_mode = 'DECEL'

            self.speed_idx = (
                decel_idx
            )

            speed_preview_distance = (
                decel_preview_distance
            )

            speed_path_curvature = (
                decel_curvature
            )

            effective_divisor = (
                decel_divisor
            )

            target_velocity = (
                decel_target_velocity
            )

        # Profile opening up, but only accelerate if actual speed has already
        # caught the requested future speed.
        elif (
            accel_target_velocity
            >
            current_profile_velocity
            +
            SPEED_TREND_EPS
            and
            accel_is_permitted
        ):

            speed_mode = 'ACCEL'

            self.speed_idx = (
                accel_idx
            )

            speed_preview_distance = (
                accel_preview_distance
            )

            speed_path_curvature = (
                accel_curvature
            )

            effective_divisor = (
                accel_divisor
            )

            target_velocity = (
                accel_target_velocity
            )

        # Profile is opening, but vehicle is still too fast.
        elif (
            accel_target_velocity
            >
            current_profile_velocity
            +
            SPEED_TREND_EPS
        ):

            speed_mode = 'COAST'

            self.speed_idx = (
                self.nearest_path_idx
            )

            speed_preview_distance = 0.0

            speed_path_curvature = (
                current_speed_curvature
            )

            effective_divisor = (
                current_divisor
            )

            target_velocity = (
                current_profile_velocity
            )

        else:

            speed_mode = 'HOLD'

            self.speed_idx = (
                self.nearest_path_idx
            )

            speed_preview_distance = 0.0

            speed_path_curvature = (
                current_speed_curvature
            )

            effective_divisor = (
                current_divisor
            )

            target_velocity = (
                current_profile_velocity
            )

        # ------------------------------------------------------------------
        # FEEDFORWARD THROTTLE - NO HARD / NEAR-HARD CUT
        #
        # ACCEL permission above already prevents the controller from looking
        # far down the CSV and reopening throttle prematurely.
        #
        # Here we simply command the selected profile feedforward.  This is
        # intentionally close to the throttle behavior from the earlier
        # collision-free 100% run.
        # ------------------------------------------------------------------

        overspeed_error = max(
            0.0,
            current_speed
            -
            target_velocity
        )

        overspeed_throttle_scale = 1.0

        throttle_command = (
            speed_control(
                target_velocity
            )
            *
            launch_throttle_scale
        )

        # ------------------------------------------------------------------
        # COMMAND OUTPUT
        # ------------------------------------------------------------------

        steering_msg = Float32()
        steering_msg.data = float(
            normalized_steering
        )

        throttle_msg = Float32()
        throttle_msg.data = float(
            throttle_command
        )

        self.steering_pub.publish(
            steering_msg
        )

        self.throttle_pub.publish(
            throttle_msg
        )

        # ------------------------------------------------------------------
        # OUR OWN optional debug topics
        # ------------------------------------------------------------------

        self.publish_debug(
            steering_lookahead,
            target_velocity,
            effective_divisor,
            prediction_distance,
            offset_target
        )

        # ------------------------------------------------------------------
        # LOW-RATE LOGGING
        # ------------------------------------------------------------------

        if (
            self.control_counter
            %
            LOG_EVERY_N
        ) == 0:

            self.get_logger().info(
                f'v={current_speed:.2f} m/s | '
                f'target={target_velocity:.2f} | '
                f'throttle={throttle_command:.3f} | '
                f'over={overspeed_error:.2f} | '
                f'th_scale={overspeed_throttle_scale:.2f} | '
                f'steer={normalized_steering:.3f} | '
                f'raw={raw_normalized_steering:.3f} | '
                f'meas={measured_normalized_steering:.3f} | '
                f'L={steering_lookahead:.2f}/'
                f'{base_steering_lookahead:.2f} m | '
                f'dirchg={direction_change_active} | '
                f'dir_prev={direction_change_preview:.2f} m | '
                f'lat_res={residual_latency_distance:.2f} m | '
                f'pred={prediction_distance:.2f}/{prediction_distance_cap:.2f} m | '
                f'inside={inside_error:.3f} m | '
                f'guard={cut_guard_blend:.2f} | '
                f'out={outward_shift:.3f} m | '
                f'mode={speed_mode} | '
                f'preview={speed_preview_distance:.2f} m | '
                f'kappa={speed_path_curvature:.2f} | '
                f'div={effective_divisor:.3f} | '
                f'launch={self.launch_state} | '
                f'fast_div={active_fast_divisor:.3f} | '
                f'PFsig={self.pf_sigma_max:.3f} | '
                f'wheelInnov={self.wheel_innovation:.2f} | '
                f'idx={self.nearest_path_idx}'
            )

        self.control_counter += 1


# =============================================================================
# MAIN
# =============================================================================

def main(
    args=None
):

    rclpy.init(
        args=args
    )

    node = RoboRacerController()

    try:

        rclpy.spin(
            node
        )

    except KeyboardInterrupt:

        pass

    finally:

        node.destroy_node()

        if rclpy.ok():

            rclpy.shutdown()


if __name__ == '__main__':
    main()
